Description: 01 - EKS Workshop Cluster creation

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: EKSWorkshop

Resources:

  Eksworkshopadmin:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: eksworkshop-admin
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - cloudformation.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  Cloud9env:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: 30
      Description: EKS-Workshop
      InstanceType: t2.small
      Name: EKSWorkshop

  Cloud9InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref 'Eksworkshopadmin']

Outputs:
  EksworkshopAdminARN:
    Value: !GetAtt Eksworkshopadmin.Arn
    
